FROM ubuntu
run apt-get update
run apt-get install -y python3 python3-pip
run apt install -y python3-flask
run mkdir /opt/app

workdir /opt/app

copy app.py /opt/app/app.py

ENTRYPOINT FLASK_APP = /opt/app/app.py flask run --host 127.0.0.1

